/* ============================================================
   Answer It — curated core, second batch
   ------------------------------------------------------------
   270 more hand-written questions, added 2026-08-26 to take the curated bank from 235 to 505.
   Written because the first batch was too thin to carry a single-category round: with ~8
   questions per (category, level) bucket, a 15-question History round used most of the bank in
   one sitting, so the freshness sort in buildPool() had nothing fresh left to reach for. This
   batch roughly doubles every bucket — 27 per category, 9 per level.

   Same row shape and the same rules as bank/curated-core.js (read its header first). It is a
   separate file purely so the diff stays reviewable; both concat onto the same global, so load
   order does not matter and either can be edited without touching the other.

   Every row here also has a matching entry in bank/curated-ar.js and bank/curated-fr.js.
   `node check.mjs` enforces that, along with the quality gate, duplicates and option collisions.
   ============================================================ */
(function () {
  const B = [
  { c:"general", l:"easy", t:"What is the freezing point of water in Celsius?", a:"0 degrees", w:["10 degrees","32 degrees","100 degrees"], r:"global", o:true },
  { c:"general", l:"easy", t:"How many sides does a hexagon have?", a:"Six", w:["Five","Seven","Eight"], r:"global", o:true },
  { c:"general", l:"easy", t:"Which animal is known as the ship of the desert?", a:"The camel", w:["The horse","The donkey","The llama"], r:"mena", o:true },
  { c:"general", l:"easy", t:"How many continents are there on Earth?", a:"Seven", w:["Five","Six","Eight"], r:"global", o:true },
  { c:"general", l:"easy", t:"Which is the fastest land animal?", a:"The cheetah", w:["The lion","The horse","The greyhound"], r:"africa", o:true },
  { c:"general", l:"easy", t:"What colour do you get by mixing red and white paint?", a:"Pink", w:["Purple","Orange","Grey"], r:"global", o:true },
  { c:"general", l:"easy", t:"What is the hardest natural substance on Earth?", a:"Diamond", w:["Granite","Steel","Quartz"], r:"global", o:true },
  { c:"general", l:"easy", t:"How many legs does an insect have?", a:"Six", w:["Four","Eight","Ten"], r:"global", o:true },
  { c:"general", l:"easy", t:"What is the largest planet in the Solar System?", a:"Jupiter", w:["Saturn","Neptune","Earth"], r:"global", o:true },
  { c:"general", l:"medium", t:"How many time zones does China officially use?", a:"One", w:["Three","Five","Eight"], r:"asia", o:true },
  { c:"general", l:"medium", t:"What does a barometer measure?", a:"Air pressure", w:["Humidity","Wind speed","Temperature"], r:"global", o:true },
  { c:"general", l:"medium", t:"Which is the largest species of shark?", a:"The whale shark", w:["The great white","The tiger shark","The hammerhead"], r:"global", o:true },
  { c:"general", l:"medium", t:"What is a group of lions called?", a:"A pride", w:["A pack","A herd","A flock"], r:"africa", o:true },
  { c:"general", l:"medium", t:"Which is the most widely learned second language in the world?", a:"English", w:["French","Spanish","Mandarin Chinese"], r:"global", o:true },
  { c:"general", l:"medium", t:"Which country produces the most rice?", a:"China", w:["India","Indonesia","Vietnam"], r:"asia", o:true },
  { c:"general", l:"medium", t:"How many degrees are there in a full circle?", a:"360", w:["180","270","400"], r:"global", o:true },
  { c:"general", l:"medium", t:"What is the study of earthquakes called?", a:"Seismology", w:["Volcanology","Meteorology","Cartography"], r:"global", o:true },
  { c:"general", l:"medium", t:"Which bird has the largest wingspan?", a:"The wandering albatross", w:["The Andean condor","The pelican","The golden eagle"], r:"global", o:true },
  { c:"general", l:"hard", t:"What is the largest living structure on Earth?", a:"The Great Barrier Reef", w:["The Amazon rainforest","Mount Everest","The Sahara"], r:"global", o:true },
  { c:"general", l:"hard", t:"What is the most abundant metal in the Earth's crust?", a:"Aluminium", w:["Iron","Copper","Magnesium"], r:"global", o:true },
  { c:"general", l:"hard", t:"Which unit measures the loudness of sound?", a:"The decibel", w:["The hertz","The watt","The lumen"], r:"global", o:true },
  { c:"general", l:"hard", t:"What does a philatelist collect?", a:"Stamps", w:["Coins","Postcards","Butterflies"], r:"global", o:true },
  { c:"general", l:"hard", t:"Which is the only bird that can fly backwards?", a:"The hummingbird", w:["The kingfisher","The swift","The falcon"], r:"latam", o:true },
  { c:"general", l:"hard", t:"Which metal has the highest melting point?", a:"Tungsten", w:["Iron","Platinum","Titanium"], n:true, r:"global", o:true },
  { c:"general", l:"hard", t:"What is the SI unit of electric current?", a:"The ampere", w:["The volt","The ohm","The watt"], r:"global", o:true },
  { c:"general", l:"hard", t:"What is the word for a phrase that reads the same forwards and backwards?", a:"A palindrome", w:["An anagram","A homonym","An acronym"], r:"global", o:true },
  { c:"general", l:"hard", t:"Which is the deepest lake in the world?", a:"Lake Baikal", w:["Lake Tanganyika","The Caspian Sea","Lake Superior"], n:true, r:"asia", o:true },
  { c:"science", l:"easy", t:"How many planets are in the Solar System?", a:"Eight", w:["Seven","Nine","Ten"], r:"global", o:true },
  { c:"science", l:"easy", t:"What is H2O better known as?", a:"Water", w:["Salt","Sugar","Air"], r:"global", o:true },
  { c:"science", l:"easy", t:"Which force pulls objects towards the ground?", a:"Gravity", w:["Friction","Magnetism","Pressure"], r:"global", o:true },
  { c:"science", l:"easy", t:"What do bees collect from flowers to make honey?", a:"Nectar", w:["Sap","Pollenless dew","Resin"], r:"global", o:true },
  { c:"science", l:"easy", t:"Which part of a plant absorbs water from the soil?", a:"The roots", w:["The leaves","The flower","The stem"], r:"global", o:true },
  { c:"science", l:"easy", t:"What happens to water when it reaches 100 degrees Celsius at sea level?", a:"It boils", w:["It freezes","It condenses","It turns to ice"], r:"global", o:true },
  { c:"science", l:"easy", t:"Which animal group do frogs belong to?", a:"Amphibians", w:["Reptiles","Mammals","Fish"], r:"global", o:true },
  { c:"science", l:"easy", t:"What is the centre of an atom called?", a:"The nucleus", w:["The shell","The orbit","The core ring"], r:"global", o:true },
  { c:"science", l:"easy", t:"Which planet is closest to the Sun?", a:"Mercury", w:["Venus","Earth","Mars"], r:"global", o:true },
  { c:"science", l:"medium", t:"What process do plants use to turn sunlight into food?", a:"Photosynthesis", w:["Respiration","Fermentation","Transpiration"], r:"global", o:true },
  { c:"science", l:"medium", t:"Which scientist proposed the theory of general relativity?", a:"Albert Einstein", w:["Isaac Newton","Niels Bohr","Max Planck"], r:"europe", o:true },
  { c:"science", l:"medium", t:"What is the most common blood type worldwide?", a:"O positive", w:["A negative","AB positive","B negative"], r:"global", o:true },
  { c:"science", l:"medium", t:"Which layer of the atmosphere contains the ozone layer?", a:"The stratosphere", w:["The troposphere","The mesosphere","The thermosphere"], r:"global", o:true },
  { c:"science", l:"medium", t:"What is the chemical symbol for iron?", a:"Fe", w:["Ir","In","Fr"], r:"global", o:true },
  { c:"science", l:"medium", t:"Which organ produces insulin?", a:"The pancreas", w:["The liver","The spleen","The thyroid"], r:"global", o:true },
  { c:"science", l:"medium", t:"How many chambers does the human heart have?", a:"Four", w:["Two","Three","Six"], r:"global", o:true },
  { c:"science", l:"medium", t:"What is the largest moon in the Solar System?", a:"Ganymede", w:["Titan","The Moon","Europa"], n:true, r:"global", o:true },
  { c:"science", l:"medium", t:"Which gas is responsible for the greenhouse effect being strongest?", a:"Carbon dioxide", w:["Argon","Neon","Helium"], r:"global", o:true },
  { c:"science", l:"hard", t:"What is the name of the sugar found in DNA?", a:"Deoxyribose", w:["Ribose","Glucose","Fructose"], n:true, r:"global", o:true },
  { c:"science", l:"hard", t:"Which particle was discovered at CERN in 2012?", a:"The Higgs boson", w:["The neutrino","The quark","The muon"], n:true, r:"europe", o:true },
  { c:"science", l:"hard", t:"What is the second most abundant element in the Earth's crust?", a:"Silicon", w:["Iron","Aluminium","Calcium"], r:"global", o:true },
  { c:"science", l:"hard", t:"Which blood cells carry oxygen around the body?", a:"Red blood cells", w:["White blood cells","Platelets","Plasma cells"], r:"global", o:true },
  { c:"science", l:"hard", t:"What is the term for an animal that is active at dusk and dawn?", a:"Crepuscular", w:["Nocturnal","Diurnal","Vespertine"], n:true, r:"global", o:true },
  { c:"science", l:"hard", t:"Which planet has the strongest winds in the Solar System?", a:"Neptune", w:["Jupiter","Saturn","Mars"], n:true, r:"global", o:true },
  { c:"science", l:"hard", t:"What is the process by which a solid turns directly into a gas?", a:"Sublimation", w:["Evaporation","Condensation","Deposition"], r:"global", o:true },
  { c:"science", l:"hard", t:"What is the boundary around a black hole beyond which nothing can escape?", a:"The event horizon", w:["The singularity","The accretion disc","The photon sphere"], n:true, r:"global", o:true },
  { c:"science", l:"hard", t:"What is the study of the interaction between living things and their environment called?", a:"Ecology", w:["Ethology","Epidemiology","Etymology"], r:"global", o:true },
  { c:"history", l:"easy", t:"Which ancient wonder still stands in Egypt today?", a:"The Great Pyramid of Giza", w:["The Hanging Gardens","The Colossus of Rhodes","The Lighthouse of Alexandria"], r:"mena", o:true },
  { c:"history", l:"easy", t:"Who was the first President of the United States?", a:"George Washington", w:["Abraham Lincoln","Thomas Jefferson","John Adams"], r:"na", o:true },
  { c:"history", l:"easy", t:"Which sea did Moses part according to the Bible and the Quran?", a:"The Red Sea", w:["The Dead Sea","The Mediterranean","The Caspian Sea"], r:"mena", o:true },
  { c:"history", l:"easy", t:"In which city did the ancient Colosseum host gladiator fights?", a:"Rome", w:["Athens","Cairo","Istanbul"], r:"europe", o:true },
  { c:"history", l:"easy", t:"Which explorer's crew completed the first voyage around the world?", a:"Ferdinand Magellan", w:["Christopher Columbus","Vasco da Gama","Marco Polo"], r:"europe", o:true },
  { c:"history", l:"easy", t:"Which ship sank on its maiden voyage in 1912?", a:"The Titanic", w:["The Lusitania","The Bismarck","The Mary Rose"], r:"global", o:true },
  { c:"history", l:"easy", t:"Which wall was built to keep out invaders from the north of China?", a:"The Great Wall", w:["The Berlin Wall","Hadrian's Wall","The Western Wall"], r:"asia", o:true },
  { c:"history", l:"easy", t:"Which language did the ancient Romans speak?", a:"Latin", w:["Greek","Etruscan","Italian"], r:"europe", o:true },
  { c:"history", l:"easy", t:"Which metal gave its name to the age that followed the Stone Age?", a:"Bronze", w:["Iron","Gold","Silver"], r:"global", o:true },
  { c:"history", l:"medium", t:"Which pharaoh's intact tomb was found in 1922?", a:"Tutankhamun", w:["Ramses II","Akhenaten","Khufu"], r:"mena", o:true },
  { c:"history", l:"medium", t:"Which North African general crossed the Alps with elephants?", a:"Hannibal", w:["Scipio","Julius Caesar","Attila"], r:"mena", o:true },
  { c:"history", l:"medium", t:"The Silk Road connected China with which other region?", a:"The Mediterranean", w:["Southern Africa","Australia","Scandinavia"], r:"asia", o:true },
  { c:"history", l:"medium", t:"Which empire was ruled by the Sultan from Topkapi Palace?", a:"The Ottoman Empire", w:["The Safavid Empire","The Mughal Empire","The Byzantine Empire"], r:"mena", o:true },
  { c:"history", l:"medium", t:"Which revolution began with the storming of the Bastille?", a:"The French Revolution", w:["The Russian Revolution","The Haitian Revolution","The American Revolution"], r:"europe", o:true },
  { c:"history", l:"medium", t:"Which country was the first in the world to give women the vote nationally?", a:"New Zealand", w:["The United States","France","Sweden"], r:"global", o:true },
  { c:"history", l:"medium", t:"Which Caribbean nation won its independence through a successful slave revolt?", a:"Haiti", w:["Cuba","Jamaica","Barbados"], r:"latam", o:true },
  { c:"history", l:"medium", t:"Which ancient library was the greatest of the classical world?", a:"The Library of Alexandria", w:["The Library of Pergamum","The Library of Nineveh","The Library of Ephesus"], r:"mena", o:true },
  { c:"history", l:"medium", t:"Who led the Cuban Revolution alongside Che Guevara?", a:"Fidel Castro", w:["Salvador Allende","Simon Bolivar","Emiliano Zapata"], r:"latam", o:true },
  { c:"history", l:"hard", t:"Which African city is home to the world's oldest continuously operating university?", a:"Fez", w:["Timbuktu","Kano","Marrakesh"], n:true, r:"africa", o:true },
  { c:"history", l:"hard", t:"Which queen led a revolt against Roman rule in Britain?", a:"Boudica", w:["Cartimandua","Zenobia","Aethelflaed"], n:true, r:"europe", o:true },
  { c:"history", l:"hard", t:"The Meiji Restoration transformed which country?", a:"Japan", w:["China","Korea","Thailand"], r:"asia", o:true },
  { c:"history", l:"hard", t:"Which kingdom controlled the gold trade of the Swahili coast from Kilwa?", a:"The Kilwa Sultanate", w:["The Kingdom of Aksum","The Kanem Empire","The Kingdom of Dahomey"], n:true, r:"africa", o:true },
  { c:"history", l:"hard", t:"Which treaty divided the New World between Spain and Portugal?", a:"The Treaty of Tordesillas", w:["The Treaty of Utrecht","The Treaty of Zaragoza","The Treaty of Madrid"], n:true, r:"europe", o:true },
  { c:"history", l:"hard", t:"Which scholar's Muqaddimah is often called the first work of sociology?", a:"Ibn Khaldun", w:["Al-Biruni","Ibn Battuta","Al-Farabi"], n:true, r:"mena", o:true },
  { c:"history", l:"hard", t:"Which empire did the Trung sisters rebel against?", a:"The Han Chinese", w:["The Mongols","The Khmer","The Japanese"], n:true, r:"asia", o:true },
  { c:"history", l:"hard", t:"Which African emperor's pilgrimage to Mecca is said to have disrupted the Egyptian economy?", a:"Mansa Musa", w:["Sundiata Keita","Askia Muhammad","Sunni Ali"], r:"africa", o:true },
  { c:"history", l:"hard", t:"The Rosetta Stone was the key to deciphering which writing system?", a:"Egyptian hieroglyphs", w:["Cuneiform","Linear B","Mayan glyphs"], r:"mena", o:true },
  { c:"geography", l:"easy", t:"Which ocean lies between Africa and Australia?", a:"The Indian Ocean", w:["The Atlantic Ocean","The Pacific Ocean","The Arctic Ocean"], r:"global", o:true },
  { c:"geography", l:"easy", t:"What is the capital of Egypt?", a:"Cairo", w:["Alexandria","Luxor","Giza"], r:"mena", o:true },
  { c:"geography", l:"easy", t:"Which continent is Brazil in?", a:"South America", w:["North America","Africa","Asia"], r:"latam", o:true },
  { c:"geography", l:"easy", t:"What is the capital of Kenya?", a:"Nairobi", w:["Mombasa","Kisumu","Dar es Salaam"], r:"africa", o:true },
  { c:"geography", l:"easy", t:"Which country is home to the Eiffel Tower?", a:"France", w:["Italy","Belgium","Spain"], r:"europe", o:true },
  { c:"geography", l:"easy", t:"Which is the largest continent by area?", a:"Asia", w:["Africa","North America","Europe"], r:"asia", o:true },
  { c:"geography", l:"easy", t:"Which country has the maple leaf on its flag?", a:"Canada", w:["Norway","Denmark","Ireland"], r:"na", o:true },
  { c:"geography", l:"easy", t:"What is the capital of India?", a:"New Delhi", w:["Mumbai","Kolkata","Chennai"], r:"asia", o:true },
  { c:"geography", l:"easy", t:"Which sea is the saltiest large body of water on Earth's surface?", a:"The Dead Sea", w:["The Red Sea","The Black Sea","The Baltic Sea"], r:"mena", o:true },
  { c:"geography", l:"medium", t:"Which river flows through Baghdad?", a:"The Tigris", w:["The Euphrates","The Jordan","The Orontes"], r:"mena", o:true },
  { c:"geography", l:"medium", t:"Which country has the most islands in the world?", a:"Sweden", w:["Indonesia","The Philippines","Japan"], n:true, r:"europe", o:true },
  { c:"geography", l:"medium", t:"Mount Kilimanjaro stands in which country?", a:"Tanzania", w:["Kenya","Uganda","Rwanda"], r:"africa", o:true },
  { c:"geography", l:"medium", t:"Which is the longest river in the world by most measures?", a:"The Nile", w:["The Amazon","The Yangtze","The Mississippi"], r:"africa", o:true },
  { c:"geography", l:"medium", t:"Which city is split between Europe and Asia?", a:"Istanbul", w:["Moscow","Cairo","Athens"], r:"mena", o:true },
  { c:"geography", l:"medium", t:"Which country's coastline is the longest in the world?", a:"Canada", w:["Russia","Indonesia","Australia"], r:"na", o:true },
  { c:"geography", l:"medium", t:"The Great Rift Valley runs mainly through which continent?", a:"Africa", w:["Asia","South America","Europe"], r:"africa", o:true },
  { c:"geography", l:"medium", t:"Which country lies directly south of the United States?", a:"Mexico", w:["Guatemala","Cuba","Belize"], r:"latam", o:true },
  { c:"geography", l:"medium", t:"Which mountain range separates Europe from Asia?", a:"The Urals", w:["The Alps","The Caucasus","The Carpathians"], r:"europe", o:true },
  { c:"geography", l:"hard", t:"Which African country has the most pyramids?", a:"Sudan", w:["Egypt","Libya","Ethiopia"], n:true, r:"africa", o:true },
  { c:"geography", l:"hard", t:"Which is the highest capital city in the world?", a:"La Paz", w:["Quito","Bogota","Kathmandu"], n:true, r:"latam", o:true },
  { c:"geography", l:"hard", t:"Which strait separates Asia from North America?", a:"The Bering Strait", w:["The Torres Strait","The Malacca Strait","The Denmark Strait"], n:true, r:"global", o:true },
  { c:"geography", l:"hard", t:"Which is the only country to border both the Atlantic Ocean and the Indian Ocean in Africa?", a:"South Africa", w:["Namibia","Morocco","Egypt"], r:"africa", o:true },
  { c:"geography", l:"hard", t:"Lake Titicaca sits on the border of Peru and which country?", a:"Bolivia", w:["Chile","Ecuador","Brazil"], r:"latam", o:true },
  { c:"geography", l:"hard", t:"Which country contains the geographic centre of the Sahara?", a:"Algeria", w:["Chad","Niger","Mali"], n:true, r:"africa", o:true },
  { c:"geography", l:"hard", t:"Which sea has no coastline, being bounded by ocean currents instead?", a:"The Sargasso Sea", w:["The Coral Sea","The Sea of Azov","The Andaman Sea"], n:true, r:"global", o:true },
  { c:"geography", l:"hard", t:"Which two countries share the island of Hispaniola?", a:"Haiti and the Dominican Republic", w:["Cuba and Jamaica","Trinidad and Tobago and Grenada","Puerto Rico and the Bahamas"], r:"latam", o:true },
  { c:"geography", l:"hard", t:"Which country is the world's largest producer of cocoa beans?", a:"Ivory Coast", w:["Ghana","Indonesia","Nigeria"], r:"africa", o:true },
  { c:"music", l:"easy", t:"Which instrument has black and white keys?", a:"The piano", w:["The guitar","The drums","The trumpet"], r:"global", o:true },
  { c:"music", l:"easy", t:"How many lines does a musical stave have?", a:"Five", w:["Four","Six","Seven"], r:"global", o:true },
  { c:"music", l:"easy", t:"Which artist is known as the Queen of Pop?", a:"Madonna", w:["Cher","Whitney Houston","Tina Turner"], r:"na", o:true },
  { c:"music", l:"easy", t:"Which instrument is played by blowing across a hole while holding it sideways?", a:"The flute", w:["The clarinet","The trumpet","The oboe"], r:"global", o:true },
  { c:"music", l:"easy", t:"What are the words of a song called?", a:"The lyrics", w:["The score","The tempo","The key"], r:"global", o:true },
  { c:"music", l:"easy", t:"Which country is K-pop from?", a:"South Korea", w:["Japan","China","Thailand"], r:"asia", o:true },
  { c:"music", l:"easy", t:"What do you call a song performed by one singer alone?", a:"A solo", w:["A duet","A chorus","A medley"], r:"global", o:true },
  { c:"music", l:"easy", t:"Which Afrobeats star recorded 'Last Last'?", a:"Burna Boy", w:["Wizkid","Rema","Asake"], r:"africa", o:true },
  { c:"music", l:"easy", t:"Which family of instruments includes the violin and the cello?", a:"Strings", w:["Brass","Woodwind","Percussion"], r:"global", o:true },
  { c:"music", l:"medium", t:"Which instrument did Louis Armstrong play?", a:"The trumpet", w:["The saxophone","The piano","The clarinet"], r:"na", o:true },
  { c:"music", l:"medium", t:"Which Italian musical term means 'very loud'?", a:"Fortissimo", w:["Pianissimo","Moderato","Andante"], r:"europe", o:true },
  { c:"music", l:"medium", t:"Which Egyptian singer is known as the Star of the East?", a:"Umm Kulthum", w:["Fairuz","Warda","Asmahan"], r:"mena", o:true },
  { c:"music", l:"medium", t:"Which Indian classical instrument has sympathetic strings and a long neck?", a:"The sitar", w:["The tabla","The veena","The sarod"], r:"asia", o:true },
  { c:"music", l:"medium", t:"Which artist released the album 'Lemonade'?", a:"Beyonce", w:["Rihanna","Adele","Alicia Keys"], r:"na", o:true },
  { c:"music", l:"medium", t:"Which dance and music style comes from Argentina?", a:"Tango", w:["Flamenco","Salsa","Cumbia"], r:"latam", o:true },
  { c:"music", l:"medium", t:"Which South African genre grew out of house music in the 2010s?", a:"Amapiano", w:["Kwaito","Bubblegum","Marabi"], r:"africa", o:true },
  { c:"music", l:"medium", t:"What does a luthier build?", a:"Stringed instruments", w:["Drums","Horns","Organs"], r:"europe", o:true },
  { c:"music", l:"medium", t:"Which Malian singer is called the Golden Voice of Africa?", a:"Salif Keita", w:["Youssou N'Dour","Ali Farka Toure","Baaba Maal"], r:"africa", o:true },
  { c:"music", l:"hard", t:"Which composer wrote the opera 'Aida', set in ancient Egypt?", a:"Verdi", w:["Puccini","Wagner","Rossini"], r:"europe", o:true },
  { c:"music", l:"hard", t:"What is the lowest male singing voice?", a:"Bass", w:["Baritone","Tenor","Countertenor"], r:"global", o:true },
  { c:"music", l:"hard", t:"Which Brazilian musician composed 'The Girl from Ipanema'?", a:"Antonio Carlos Jobim", w:["Joao Gilberto","Gilberto Gil","Caetano Veloso"], n:true, r:"latam", o:true },
  { c:"music", l:"hard", t:"Which instrument family does the saxophone belong to?", a:"Woodwind", w:["Brass","Percussion","Strings"], r:"global", o:true },
  { c:"music", l:"hard", t:"Which Ethiopian musician pioneered Ethio-jazz?", a:"Mulatu Astatke", w:["Mahmoud Ahmed","Aster Aweke","Gigi"], n:true, r:"africa", o:true },
  { c:"music", l:"hard", t:"Which major key has no sharps and no flats?", a:"C major", w:["G major","F major","D major"], r:"global", o:true },
  { c:"music", l:"hard", t:"Which 1969 festival became the symbol of the counterculture era?", a:"Woodstock", w:["Monterey Pop","Isle of Wight","Altamont"], r:"na", o:true },
  { c:"music", l:"hard", t:"Which is the largest instrument in an orchestra's string section?", a:"The double bass", w:["The cello","The viola","The harp"], r:"global", o:true },
  { c:"music", l:"hard", t:"In which decade did hip hop emerge in New York?", a:"The 1970s", w:["The 1950s","The 1960s","The 1990s"], r:"na", o:true },
  { c:"screen", l:"easy", t:"What colour is the Hulk?", a:"Green", w:["Blue","Red","Purple"], r:"global", o:true },
  { c:"screen", l:"easy", t:"Which animated film features a snowman named Olaf?", a:"Frozen", w:["Moana","Tangled","Encanto"], r:"global", o:true },
  { c:"screen", l:"easy", t:"Which boy wizard has a lightning-shaped scar?", a:"Harry Potter", w:["Percy Jackson","Frodo Baggins","Peter Parker"], r:"europe", o:true },
  { c:"screen", l:"easy", t:"Which superhero comes from the planet Krypton?", a:"Superman", w:["Batman","Thor","Aquaman"], r:"na", o:true },
  { c:"screen", l:"easy", t:"Which series features a girl known only as Eleven?", a:"Stranger Things", w:["Dark","The OA","Wednesday"], r:"na", o:true },
  { c:"screen", l:"easy", t:"In 'Finding Nemo', what kind of fish is Nemo?", a:"A clownfish", w:["A goldfish","A shark","A dolphin"], r:"global", o:true },
  { c:"screen", l:"easy", t:"Which film series follows a ring that must be destroyed in a volcano?", a:"The Lord of the Rings", w:["Narnia","Eragon","Willow"], r:"europe", o:true },
  { c:"screen", l:"easy", t:"Which animated film tells the story of Moses?", a:"The Prince of Egypt", w:["Aladdin","Hercules","Mulan"], r:"mena", o:true },
  { c:"screen", l:"easy", t:"What colour is Darth Vader's lightsaber?", a:"Red", w:["Blue","Green","Purple"], r:"global", o:true },
  { c:"screen", l:"medium", t:"Which Indian film won the 2023 Oscar for Best Original Song?", a:"RRR", w:["Gully Boy","Lagaan","Dangal"], r:"asia", o:true },
  { c:"screen", l:"medium", t:"Which director made 'Get Out' and 'Us'?", a:"Jordan Peele", w:["Ryan Coogler","Barry Jenkins","Spike Lee"], r:"na", o:true },
  { c:"screen", l:"medium", t:"Which country is the setting of the series 'Squid Game'?", a:"South Korea", w:["Japan","China","Taiwan"], r:"asia", o:true },
  { c:"screen", l:"medium", t:"Which actress played Katniss in 'The Hunger Games'?", a:"Jennifer Lawrence", w:["Emma Watson","Shailene Woodley","Kristen Stewart"], r:"na", o:true },
  { c:"screen", l:"medium", t:"Which Studio Ghibli film follows two sisters and a giant forest spirit?", a:"My Neighbour Totoro", w:["Ponyo","Princess Mononoke","Howl's Moving Castle"], r:"asia", o:true },
  { c:"screen", l:"medium", t:"Which Nigerian actress directed the film 'Lionheart'?", a:"Genevieve Nnaji", w:["Funke Akindele","Omotola Jalade","Rita Dominic"], r:"africa", o:true },
  { c:"screen", l:"medium", t:"Which film gave us the line 'I'll be back'?", a:"The Terminator", w:["RoboCop","Predator","Total Recall"], r:"na", o:true },
  { c:"screen", l:"medium", t:"Which streaming platform produced 'Stranger Things'?", a:"Netflix", w:["Amazon Prime Video","Disney+","HBO"], r:"na", o:true },
  { c:"screen", l:"medium", t:"Which Pixar film is set mostly inside a girl's mind?", a:"Inside Out", w:["Soul","Coco","Up"], r:"na", o:true },
  { c:"screen", l:"hard", t:"Which Egyptian director made 'Cairo Station'?", a:"Youssef Chahine", w:["Yousry Nasrallah","Mohamed Diab","Marwan Hamed"], n:true, r:"mena", o:true },
  { c:"screen", l:"hard", t:"Which performer has won the most Academy Awards for acting?", a:"Katharine Hepburn", w:["Meryl Streep","Jack Nicholson","Daniel Day-Lewis"], n:true, r:"na", o:true },
  { c:"screen", l:"hard", t:"Which Senegalese film is regarded as the first feature by a Black African director?", a:"Black Girl", w:["Yeelen","Touki Bouki","Xala"], n:true, r:"africa", o:true },
  { c:"screen", l:"hard", t:"Which film franchise features the character Ellen Ripley?", a:"Alien", w:["Predator","The Terminator","Blade Runner"], r:"na", o:true },
  { c:"screen", l:"hard", t:"Which Iranian director won an Oscar with 'A Separation'?", a:"Asghar Farhadi", w:["Abbas Kiarostami","Jafar Panahi","Majid Majidi"], n:true, r:"mena", o:true },
  { c:"screen", l:"hard", t:"Which was the first non-English language film to win Best Picture?", a:"Parasite", w:["Roma","Amour","Crouching Tiger, Hidden Dragon"], r:"asia", o:true },
  { c:"screen", l:"hard", t:"Which Hitchcock film features a shower scene at the Bates Motel?", a:"Psycho", w:["Vertigo","The Birds","Rear Window"], r:"na", o:true },
  { c:"screen", l:"hard", t:"Which Japanese director made 'Seven Samurai'?", a:"Akira Kurosawa", w:["Yasujiro Ozu","Kenji Mizoguchi","Hayao Miyazaki"], r:"asia", o:true },
  { c:"screen", l:"hard", t:"In 'The Matrix', which coloured pill does Neo take to learn the truth?", a:"Red", w:["Blue","Green","White"], r:"na", o:true },
  { c:"games", l:"easy", t:"In chess, which piece must be protected at all costs?", a:"The king", w:["The queen","The rook","The bishop"], r:"global", o:true },
  { c:"games", l:"easy", t:"What shape is a standard playing die?", a:"A cube", w:["A pyramid","A sphere","A cylinder"], r:"global", o:true },
  { c:"games", l:"easy", t:"In which game do players clear lines with falling blocks?", a:"Tetris", w:["Candy Crush","Bejeweled","Sudoku"], r:"europe", o:true },
  { c:"games", l:"easy", t:"Which company created Super Mario?", a:"Nintendo", w:["Sony","Sega","Microsoft"], r:"asia", o:true },
  { c:"games", l:"easy", t:"Which football video game series is made by EA?", a:"FIFA", w:["Pro Evolution Soccer","Football Manager","Rocket League"], r:"global", o:true },
  { c:"games", l:"easy", t:"How many players does a game of chess need?", a:"Two", w:["One","Three","Four"], r:"global", o:true },
  { c:"games", l:"easy", t:"Which anime follows a boy who dreams of becoming Hokage?", a:"Naruto", w:["Bleach","One Piece","Dragon Ball"], r:"asia", o:true },
  { c:"games", l:"easy", t:"What do you usually roll to move in a board game?", a:"Dice", w:["Cards","Coins","Spinners"], r:"global", o:true },
  { c:"games", l:"easy", t:"Which game is played on a 19 by 19 grid with black and white stones?", a:"Go", w:["Chess","Checkers","Backgammon"], r:"asia", o:true },
  { c:"games", l:"medium", t:"Which video game character is a fast blue hedgehog?", a:"Sonic", w:["Crash Bandicoot","Spyro","Klonoa"], r:"asia", o:true },
  { c:"games", l:"medium", t:"Which game series is set in the land of Hyrule?", a:"The Legend of Zelda", w:["Final Fantasy","Dragon Quest","Chrono Trigger"], r:"asia", o:true },
  { c:"games", l:"medium", t:"Mancala, one of the oldest board game families, originated on which continent?", a:"Africa", w:["Asia","Europe","South America"], r:"africa", o:true },
  { c:"games", l:"medium", t:"Which anime follows Goku and a search for seven magical spheres?", a:"Dragon Ball", w:["Naruto","Bleach","Hunter x Hunter"], r:"asia", o:true },
  { c:"games", l:"medium", t:"Which esports game is played five against five on Summoner's Rift?", a:"League of Legends", w:["Dota 2","Valorant","Overwatch"], r:"global", o:true },
  { c:"games", l:"medium", t:"Which handheld console did Nintendo launch in 1989?", a:"The Game Boy", w:["The Game Gear","The Neo Geo Pocket","The PSP"], r:"asia", o:true },
  { c:"games", l:"medium", t:"In Scrabble, which letter is worth ten points alongside Z?", a:"Q", w:["X","J","K"], r:"global", o:true },
  { c:"games", l:"medium", t:"Which 2017 game popularised the hundred-player battle royale?", a:"PUBG", w:["Fortnite","Apex Legends","Warzone"], r:"asia", o:true },
  { c:"games", l:"medium", t:"Which Japanese franchise features a creature called Pikachu?", a:"Pokemon", w:["Digimon","Yu-Gi-Oh","Beyblade"], r:"asia", o:true },
  { c:"games", l:"hard", t:"Which game engine powers Fortnite?", a:"Unreal Engine", w:["Unity","Godot","CryEngine"], n:true, r:"na", o:true },
  { c:"games", l:"hard", t:"Which chess opening begins 1.e4 e5 2.Nf3 Nc6 3.Bb5?", a:"The Ruy Lopez", w:["The Sicilian Defence","The French Defence","The Italian Game"], n:true, r:"europe", o:true },
  { c:"games", l:"hard", t:"Which ancient Egyptian board game is among the oldest known?", a:"Senet", w:["Backgammon","Nine Men's Morris","Pachisi"], n:true, r:"mena", o:true },
  { c:"games", l:"hard", t:"Which studio created Dark Souls?", a:"FromSoftware", w:["Team Ninja","Platinum Games","Atlus"], n:true, r:"asia", o:true },
  { c:"games", l:"hard", t:"Which anime by Hirohiko Araki follows the Joestar family?", a:"JoJo's Bizarre Adventure", w:["Berserk","Vinland Saga","Hellsing"], n:true, r:"asia", o:true },
  { c:"games", l:"hard", t:"In Go, a group of stones with two eyes is said to be what?", a:"Alive", w:["Atari","Ko","Seki"], n:true, r:"asia", o:true },
  { c:"games", l:"hard", t:"Which 1993 shooter did the most to popularise the first-person genre?", a:"Doom", w:["Quake","Half-Life","Duke Nukem 3D"], r:"na", o:true },
  { c:"games", l:"hard", t:"Oware, played across West Africa, belongs to which family of board games?", a:"Mancala", w:["Chess variants","Race games","Tile games"], n:true, r:"africa", o:true },
  { c:"games", l:"hard", t:"Which studio developed The Sims?", a:"Maxis", w:["Blizzard","Rockstar","Valve"], r:"na", o:true },
  { c:"sport", l:"easy", t:"How many holes are played in a full round of golf?", a:"18", w:["9","12","24"], r:"global", o:true },
  { c:"sport", l:"easy", t:"Which sport is played with a shuttlecock?", a:"Badminton", w:["Tennis","Squash","Table tennis"], r:"asia", o:true },
  { c:"sport", l:"easy", t:"In which sport do you score a try?", a:"Rugby", w:["Football","Hockey","Basketball"], r:"global", o:true },
  { c:"sport", l:"easy", t:"How many points is a basketball shot from beyond the arc?", a:"Three", w:["Two","One","Four"], r:"global", o:true },
  { c:"sport", l:"easy", t:"In which country is the Olympic flame lit before each Games?", a:"Greece", w:["Italy","France","Switzerland"], r:"europe", o:true },
  { c:"sport", l:"easy", t:"Which card sends a footballer off the pitch?", a:"The red card", w:["The yellow card","The blue card","The black card"], r:"global", o:true },
  { c:"sport", l:"easy", t:"Which sport is Serena Williams famous for?", a:"Tennis", w:["Golf","Athletics","Swimming"], r:"na", o:true },
  { c:"sport", l:"easy", t:"How many rounds does a standard professional boxing title fight last?", a:"Twelve", w:["Eight","Ten","Fifteen"], r:"global", o:true },
  { c:"sport", l:"easy", t:"Which swimming stroke is swum lying on your back?", a:"Backstroke", w:["Butterfly","Breaststroke","Freestyle"], r:"global", o:true },
  { c:"sport", l:"medium", t:"Which country won the first FIFA World Cup in 1930?", a:"Uruguay", w:["Brazil","Argentina","Italy"], r:"latam", o:true },
  { c:"sport", l:"medium", t:"How often are the Summer Olympic Games held?", a:"Every four years", w:["Every two years","Every three years","Every five years"], r:"global", o:true },
  { c:"sport", l:"medium", t:"Which African country reached the 2022 World Cup semi-finals?", a:"Morocco", w:["Senegal","Ghana","Cameroon"], r:"africa", o:true },
  { c:"sport", l:"medium", t:"In cricket, what is a batter's score of zero called?", a:"A duck", w:["A love","A blank","A nil"], r:"asia", o:true },
  { c:"sport", l:"medium", t:"Which country has dominated Olympic table tennis?", a:"China", w:["Japan","South Korea","Germany"], r:"asia", o:true },
  { c:"sport", l:"medium", t:"How long is an Olympic swimming pool?", a:"50 metres", w:["25 metres","100 metres","75 metres"], r:"global", o:true },
  { c:"sport", l:"medium", t:"How many hurdles does a runner clear in the 110 metres hurdles?", a:"Ten", w:["Eight","Twelve","Fourteen"], r:"global", o:true },
  { c:"sport", l:"medium", t:"Which martial art awards an ippon for a winning throw?", a:"Judo", w:["Karate","Taekwondo","Aikido"], r:"asia", o:true },
  { c:"sport", l:"medium", t:"Which Ethiopian runner won the 1960 Olympic marathon barefoot?", a:"Abebe Bikila", w:["Haile Gebrselassie","Kenenisa Bekele","Miruts Yifter"], r:"africa", o:true },
  { c:"sport", l:"hard", t:"Which tennis Grand Slam is played on clay?", a:"The French Open", w:["Wimbledon","The Australian Open","The US Open"], r:"europe", o:true },
  { c:"sport", l:"hard", t:"Which country has won the Africa Cup of Nations the most times?", a:"Egypt", w:["Cameroon","Ghana","Nigeria"], r:"africa", o:true },
  { c:"sport", l:"hard", t:"What is the diameter of a basketball hoop?", a:"18 inches", w:["15 inches","20 inches","24 inches"], n:true, r:"na", o:true },
  { c:"sport", l:"hard", t:"How many players are on the pitch per team in rugby union?", a:"Fifteen", w:["Thirteen","Eleven","Seventeen"], r:"global", o:true },
  { c:"sport", l:"hard", t:"World Aquatics, formerly FINA, governs which sport?", a:"Swimming", w:["Rowing","Sailing","Fencing"], r:"global", o:true },
  { c:"sport", l:"hard", t:"Which country won the first Rugby World Cup in 1987?", a:"New Zealand", w:["Australia","France","South Africa"], r:"global", o:true },
  { c:"sport", l:"hard", t:"In Formula One, what does the chequered flag signal?", a:"The end of the race", w:["A penalty","A safety car","A restart"], r:"europe", o:true },
  { c:"sport", l:"hard", t:"What is the maximum score in a single game of ten-pin bowling?", a:"300", w:["200","250","360"], n:true, r:"na", o:true },
  { c:"sport", l:"hard", t:"What object is the Ashes trophy, contested by England and Australia in cricket?", a:"A small terracotta urn", w:["A silver cup","A golden bat","A wooden shield"], n:true, r:"global", o:true },
  { c:"arts", l:"easy", t:"Which painter cut off part of his own ear?", a:"Vincent van Gogh", w:["Claude Monet","Paul Gauguin","Edgar Degas"], r:"europe", o:true },
  { c:"arts", l:"easy", t:"What is a sculpture made of fired clay called?", a:"Terracotta", w:["Marble","Bronze","Fresco"], r:"global", o:true },
  { c:"arts", l:"easy", t:"Which three colours are the primary colours of paint?", a:"Red, yellow and blue", w:["Red, green and blue","Orange, green and purple","Black, white and grey"], r:"global", o:true },
  { c:"arts", l:"easy", t:"Who wrote the play 'Hamlet'?", a:"William Shakespeare", w:["Anton Chekhov","Henrik Ibsen","Moliere"], r:"europe", o:true },
  { c:"arts", l:"easy", t:"Which Paris museum houses the Mona Lisa?", a:"The Louvre", w:["The Prado","The Uffizi","The Hermitage"], r:"europe", o:true },
  { c:"arts", l:"easy", t:"What do you call a picture an artist paints of themselves?", a:"A self-portrait", w:["A landscape","A still life","A mural"], r:"global", o:true },
  { c:"arts", l:"easy", t:"Which ancient Greek epic tells of the Trojan War?", a:"The Iliad", w:["The Odyssey","The Aeneid","Metamorphoses"], r:"europe", o:true },
  { c:"arts", l:"easy", t:"Which instrument is traditionally used for Chinese calligraphy?", a:"A brush", w:["A quill","A fountain pen","A reed"], r:"asia", o:true },
  { c:"arts", l:"easy", t:"What is a very large painting made directly on a wall called?", a:"A mural", w:["A portrait","A sketch","A collage"], r:"latam", o:true },
  { c:"arts", l:"medium", t:"Which Dutch painter made 'Girl with a Pearl Earring'?", a:"Johannes Vermeer", w:["Rembrandt","Frans Hals","Vincent van Gogh"], r:"europe", o:true },
  { c:"arts", l:"medium", t:"Which Japanese woodblock print shows a huge wave off Kanagawa?", a:"The Great Wave", w:["Red Fuji","The Plum Garden","Sudden Shower"], r:"asia", o:true },
  { c:"arts", l:"medium", t:"Which Russian novelist wrote 'War and Peace'?", a:"Leo Tolstoy", w:["Fyodor Dostoevsky","Anton Chekhov","Ivan Turgenev"], r:"europe", o:true },
  { c:"arts", l:"medium", t:"Which Palestinian poet wrote 'Identity Card'?", a:"Mahmoud Darwish", w:["Nizar Qabbani","Adonis","Tawfiq Ziad"], r:"mena", o:true },
  { c:"arts", l:"medium", t:"What is the Japanese three-line poem form called?", a:"Haiku", w:["Tanka","A sonnet","An ode"], r:"asia", o:true },
  { c:"arts", l:"medium", t:"Which architect designed the Sagrada Familia?", a:"Antoni Gaudi", w:["Le Corbusier","Frank Lloyd Wright","Norman Foster"], r:"europe", o:true },
  { c:"arts", l:"medium", t:"Which Chilean poet won the Nobel Prize in Literature in 1971?", a:"Pablo Neruda", w:["Gabriela Mistral","Octavio Paz","Cesar Vallejo"], r:"latam", o:true },
  { c:"arts", l:"medium", t:"What is the technique of painting onto wet plaster called?", a:"Fresco", w:["Gouache","Impasto","Encaustic"], r:"europe", o:true },
  { c:"arts", l:"medium", t:"Which Indian epic follows Prince Rama?", a:"The Ramayana", w:["The Mahabharata","The Vedas","The Puranas"], r:"asia", o:true },
  { c:"arts", l:"hard", t:"Which Sudanese writer wrote 'Season of Migration to the North'?", a:"Tayeb Salih", w:["Naguib Mahfouz","Leila Aboulela","Amir Tag Elsir"], n:true, r:"mena", o:true },
  { c:"arts", l:"hard", t:"Which artist created the sculpture 'The Thinker'?", a:"Auguste Rodin", w:["Camille Claudel","Constantin Brancusi","Alberto Giacometti"], r:"europe", o:true },
  { c:"arts", l:"hard", t:"Which art movement is Frida Kahlo most associated with?", a:"Surrealism", w:["Cubism","Impressionism","Expressionism"], r:"latam", o:true },
  { c:"arts", l:"hard", t:"Which Zimbabwean stone-carving tradition won international recognition in the 20th century?", a:"Shona sculpture", w:["Makonde carving","Nok terracotta","Benin bronze"], n:true, r:"africa", o:true },
  { c:"arts", l:"hard", t:"Which Japanese author won the Nobel Prize in Literature in 1968?", a:"Yasunari Kawabata", w:["Yukio Mishima","Kenzaburo Oe","Junichiro Tanizaki"], n:true, r:"asia", o:true },
  { c:"arts", l:"hard", t:"Which Renaissance artist painted the ceiling of the Sistine Chapel?", a:"Michelangelo", w:["Raphael","Leonardo da Vinci","Titian"], r:"europe", o:true },
  { c:"arts", l:"hard", t:"Which Argentine writer wrote the story collection 'Ficciones'?", a:"Jorge Luis Borges", w:["Julio Cortazar","Ernesto Sabato","Adolfo Bioy Casares"], n:true, r:"latam", o:true },
  { c:"arts", l:"hard", t:"What is the technique that gives a painting depth using a vanishing point?", a:"Linear perspective", w:["Chiaroscuro","Sfumato","Foreshortening"], n:true, r:"europe", o:true },
  { c:"arts", l:"hard", t:"Which West African epic is recited by griots and tells of a founding king?", a:"The Epic of Sundiata", w:["The Epic of Gilgamesh","The Kebra Nagast","The Book of Dede Korkut"], n:true, r:"africa", o:true },
  { c:"culture", l:"easy", t:"Which meal breaks the fast each evening during Ramadan?", a:"Iftar", w:["Suhoor","Eid","Zakat"], r:"mena", o:true },
  { c:"culture", l:"easy", t:"What is the traditional Japanese robe called?", a:"A kimono", w:["A sari","A kaftan","A poncho"], r:"asia", o:true },
  { c:"culture", l:"easy", t:"Which country is the home of pizza and pasta?", a:"Italy", w:["Greece","Spain","Portugal"], r:"europe", o:true },
  { c:"culture", l:"easy", t:"What is the main ingredient of hummus?", a:"Chickpeas", w:["Lentils","Broad beans","Green peas"], r:"mena", o:true },
  { c:"culture", l:"easy", t:"Which drink is made by steeping leaves in hot water?", a:"Tea", w:["Coffee","Cocoa","Juice"], r:"asia", o:true },
  { c:"culture", l:"easy", t:"Which Indian garment is draped from a single long piece of cloth?", a:"A sari", w:["A kimono","An abaya","A kente cloth"], r:"asia", o:true },
  { c:"culture", l:"easy", t:"Which festival marks the end of Ramadan?", a:"Eid al-Fitr", w:["Eid al-Adha","Ashura","Mawlid"], r:"mena", o:true },
  { c:"culture", l:"easy", t:"What is a taco traditionally wrapped in?", a:"A tortilla", w:["A baguette","A pita","A naan"], r:"latam", o:true },
  { c:"culture", l:"easy", t:"Which eating utensils are traditional across much of East Asia?", a:"Chopsticks", w:["Forks","Spoons","Knives"], r:"asia", o:true },
  { c:"culture", l:"medium", t:"Which country's tea ceremony is known as chanoyu?", a:"Japan", w:["China","Korea","Vietnam"], r:"asia", o:true },
  { c:"culture", l:"medium", t:"Which spice gives many curries their yellow colour?", a:"Turmeric", w:["Cumin","Paprika","Coriander"], r:"asia", o:true },
  { c:"culture", l:"medium", t:"What is the Ethiopian flatbread served under stews?", a:"Injera", w:["Chapati","Roti","Lavash"], r:"africa", o:true },
  { c:"culture", l:"medium", t:"Which animal begins the twelve-year Chinese zodiac cycle?", a:"The rat", w:["The dragon","The tiger","The ox"], r:"asia", o:true },
  { c:"culture", l:"medium", t:"Which Moroccan dish is named after the conical pot it is cooked in?", a:"Tagine", w:["Couscous","Harira","Pastilla"], r:"mena", o:true },
  { c:"culture", l:"medium", t:"Which greeting meaning 'peace' is used across the Arab world?", a:"Salaam", w:["Shalom","Namaste","Sawubona"], r:"mena", o:true },
  { c:"culture", l:"medium", t:"Which bitter nut is a traditional gift of welcome in West Africa?", a:"The kola nut", w:["The cashew","The shea nut","The tiger nut"], r:"africa", o:true },
  { c:"culture", l:"medium", t:"What is the Korean side dish of fermented vegetables called?", a:"Kimchi", w:["Miso","Natto","Tofu"], r:"asia", o:true },
  { c:"culture", l:"medium", t:"Which West African stew is thickened with ground peanuts?", a:"Groundnut stew", w:["Jollof rice","Fufu","Suya"], r:"africa", o:true },
  { c:"culture", l:"hard", t:"Which country celebrates its traditional new year, Songkran, with water fights?", a:"Thailand", w:["Cambodia","Laos","Myanmar"], n:true, r:"asia", o:true },
  { c:"culture", l:"hard", t:"What is the Japanese idea of finding beauty in imperfection called?", a:"Wabi-sabi", w:["Ikigai","Kaizen","Mono no aware"], n:true, r:"asia", o:true },
  { c:"culture", l:"hard", t:"Which grain did the Inca call the mother grain?", a:"Quinoa", w:["Maize","Amaranth","Barley"], r:"latam", o:true },
  { c:"culture", l:"hard", t:"Which fermented Ethiopian honey wine is served at celebrations?", a:"Tej", w:["Tella","Areki","Borde"], n:true, r:"africa", o:true },
  { c:"culture", l:"hard", t:"Which script is used to write Amharic?", a:"Ge'ez", w:["Arabic","Latin","Cyrillic"], n:true, r:"africa", o:true },
  { c:"culture", l:"hard", t:"What is the Japanese art of mending pottery with gold called?", a:"Kintsugi", w:["Raku","Shibori","Sashiko"], n:true, r:"asia", o:true },
  { c:"culture", l:"hard", t:"Which hooded cloak is traditionally worn in Morocco?", a:"The djellaba", w:["The kaftan","The abaya","The dashiki"], r:"mena", o:true },
  { c:"culture", l:"hard", t:"Which country's Day of Silence, Nyepi, closes its airport for a full day?", a:"Indonesia", w:["Thailand","India","Nepal"], n:true, r:"asia", o:true },
  { c:"culture", l:"hard", t:"Which Andean fibre comes from a camelid relative of the llama?", a:"Alpaca wool", w:["Cashmere","Mohair","Angora"], n:true, r:"latam", o:true },

  ];
  globalThis.ANSWER_IT_CURATED = (globalThis.ANSWER_IT_CURATED || []).concat(B);
})();
