/* ============================================================
   Answer It - curated Islamic Knowledge bank
   ------------------------------------------------------------
   Same shape and rules as bank/curated-core.js / curated-extra.js (see that file's header and
   QUESTIONS.md §4) - this is its own file purely to keep the diff reviewable, the split has no
   other meaning. Concats onto the same globalThis.ANSWER_IT_CURATED, loaded the same way over
   file:// and as a side-effect import in the Worker.

   Scope, deliberately: broadly-known, respectful, non-sectarian material a general adult crowd
   (Muslim or not) can have a real shot at - the Five Pillars, Ramadan/Eid, Hajj, the Quran, the
   Hijri calendar, major mosques and cities, the Islamic Golden Age, and the historical empires
   built on it. Nothing here turns on a theologically contested position or a succession dispute -
   that material simply isn't included, on the same "would a smart person who isn't a specialist
   have a shot" test every other category already uses (QUESTIONS.md house rule #1).

   Row shape (see bank/curated-core.js for the full legend):
     c:"islamic"  l: easy|medium|hard  t: question  a: correct answer  w: three wrong options
     n: true -> eligible for native Hell (§5.2)     r: region flavour   o: true -> open-answer eligible
   ============================================================ */
(function () {
  const B = [

  /* ---------------- easy ---------------- */
  { c:"islamic", l:"easy", t:"What is the name of the Islamic holy book?", a:"The Quran", w:["The Torah","The Gospel","The Talmud"], r:"global", o:true },
  { c:"islamic", l:"easy", t:"In which city is the Kaaba located?", a:"Mecca", w:["Medina","Jerusalem","Cairo"], r:"mena", o:true },
  { c:"islamic", l:"easy", t:"What is the ninth month of the Islamic calendar, during which Muslims fast?", a:"Ramadan", w:["Shawwal","Muharram","Rajab"], r:"global", o:true },
  { c:"islamic", l:"easy", t:"How many times a day do practising Muslims perform the ritual prayer?", a:"Five", w:["Three","Seven","Two"], r:"global", o:true },
  { c:"islamic", l:"easy", t:"What is the Muslim place of worship called?", a:"A mosque", w:["A synagogue","A temple","A shrine"], r:"global", o:true },
  { c:"islamic", l:"easy", t:"What is the call to prayer, announced from a mosque, called?", a:"The Adhan", w:["The Khutbah","The Fatwa","The Dua"], r:"global", o:true },
  { c:"islamic", l:"easy", t:"Which festival marks the end of the month of Ramadan?", a:"Eid al-Fitr", w:["Eid al-Adha","Ashura","Mawlid"], r:"global", o:true },
  { c:"islamic", l:"easy", t:"Which festival, sometimes called the 'Festival of Sacrifice', falls during the Hajj season?", a:"Eid al-Adha", w:["Eid al-Fitr","Laylat al-Qadr","Isra and Mi'raj"], r:"global", o:true },
  { c:"islamic", l:"easy", t:"What is the name of the annual Islamic pilgrimage every able Muslim is expected to make once in their life?", a:"The Hajj", w:["The Umrah","The Hijra","The Isra"], r:"mena", o:true },
  { c:"islamic", l:"easy", t:"Besides Mecca, which city is Islam's second-holiest, home to the Prophet's Mosque?", a:"Medina", w:["Jerusalem","Baghdad","Damascus"], r:"mena", o:true },
  { c:"islamic", l:"easy", t:"What word do Muslims use for God?", a:"Allah", w:["Yahweh","Brahman","Elohim"], r:"global", o:true },
  { c:"islamic", l:"easy", t:"What shape is the Kaaba, the building Muslims face during prayer?", a:"A cube", w:["A dome","A pyramid","A sphere"], r:"mena", o:true },
  { c:"islamic", l:"easy", t:"What is a chapter of the Quran called?", a:"A surah", w:["A psalm","A parable","A canticle"], r:"global", o:true },
  { c:"islamic", l:"easy", t:"What is the Islamic declaration of faith called?", a:"The Shahada", w:["The Zakat","The Sawm","The Adhan"], r:"global", o:true },
  { c:"islamic", l:"easy", t:"What is the Islamic practice of giving a portion of one's wealth to charity called?", a:"Zakat", w:["Sadaqah","Waqf","Khums"], n:true, r:"global", o:true },
  { c:"islamic", l:"easy", t:"What is the direction Muslims face during prayer called?", a:"The qibla", w:["The mihrab","The minbar","The iwan"], n:true, r:"global", o:true },
  { c:"islamic", l:"easy", t:"What is the tower attached to a mosque, from which the call to prayer is traditionally given, called?", a:"A minaret", w:["A steeple","A pagoda","A campanile"], r:"global", o:true },
  { c:"islamic", l:"easy", t:"In which language was the Quran originally revealed?", a:"Arabic", w:["Hebrew","Persian","Aramaic"], r:"global", o:true },
  { c:"islamic", l:"easy", t:"What is the person who leads the congregational prayer in a mosque called?", a:"An imam", w:["A rabbi","A bishop","A monk"], r:"global", o:true },
  { c:"islamic", l:"easy", t:"During Ramadan, at what time of day does the daily fast typically end?", a:"Sunset", w:["Noon","Midnight","Sunrise"], r:"global", o:true },
  { c:"islamic", l:"easy", t:"What is the pre-dawn meal eaten before the daily fast during Ramadan called?", a:"Suhoor", w:["Iftar","Tarawih","Zakat"], n:true, r:"global", o:true },
  { c:"islamic", l:"easy", t:"What is the meal that breaks the daily fast at sunset during Ramadan called?", a:"Iftar", w:["Suhoor","Tarawih","Qiyam"], r:"global", o:true },
  { c:"islamic", l:"easy", t:"Which prophet do Muslims regard as the final messenger of Islam?", a:"Muhammad", w:["Ibrahim (Abraham)","Musa (Moses)","Isa (Jesus)"], r:"global", o:true },
  { c:"islamic", l:"easy", t:"Which of Islam's holy sites is located in Jerusalem?", a:"Al-Aqsa Mosque", w:["The Blue Mosque","The Great Mosque of Kairouan","The Sultan Ahmed Mosque"], r:"mena", o:true },
  { c:"islamic", l:"easy", t:"What is the crescent moon, often paired with a star, widely used as a symbol of?", a:"Islam", w:["Judaism","Buddhism","Sikhism"], r:"global" },
  { c:"islamic", l:"easy", t:"Roughly what fraction of a day do Muslims typically abstain from food and drink during Ramadan?", a:"Most of the daylight hours", w:["Only the morning", "Only after midnight","The entire 24 hours"], r:"global" },
  { c:"islamic", l:"easy", t:"What is a mosque's prayer niche, which indicates the direction of Mecca, called?", a:"The mihrab", w:["The minbar","The qibla","The minaret"], n:true, r:"global", o:true },
  { c:"islamic", l:"easy", t:"What is the pulpit from which a mosque's Friday sermon is delivered called?", a:"The minbar", w:["The mihrab","The lectern","The ambo"], n:true, r:"global", o:true },
  { c:"islamic", l:"easy", t:"What is the Friday congregational prayer, unique to that day of the week, called?", a:"Jumu'ah", w:["Tarawih","Witr","Qiyam"], n:true, r:"global", o:true },
  { c:"islamic", l:"easy", t:"Which holy book do Muslims believe was revealed to the Prophet Muhammad over roughly 23 years?", a:"The Quran", w:["The Hadith","The Sunnah","The Sirah"], r:"global" },
  { c:"islamic", l:"easy", t:"What is the year Muhammad migrated from Mecca to Medina, which starts the Islamic calendar, called?", a:"The Hijra", w:["The Isra","The Mi'raj","The Fath"], n:true, r:"mena", o:true },
  { c:"islamic", l:"easy", t:"What is the name of the Islamic calendar, based on the phases of the moon?", a:"The Hijri calendar", w:["The Gregorian calendar","The Julian calendar","The Solar Hijri calendar"], r:"global" },
  { c:"islamic", l:"easy", t:"Which patriarch do Muslims, Christians and Jews all trace their Abrahamic faiths back to?", a:"Ibrahim (Abraham)", w:["Musa (Moses)","Nuh (Noah)","Dawud (David)"], r:"global", o:true },
  { c:"islamic", l:"easy", t:"What number of pillars make up the core practices of Islam?", a:"Five", w:["Four","Six","Seven"], r:"global", o:true },
  { c:"islamic", l:"easy", t:"What is the Islamic term for the collected sayings and actions of the Prophet Muhammad?", a:"Hadith", w:["Fiqh","Tafsir","Ijma"], n:true, r:"global", o:true },
  { c:"islamic", l:"easy", t:"What greeting, meaning 'peace be upon you', is commonly used among Muslims?", a:"As-salamu alaykum", w:["Shalom aleichem","Namaste","Bismillah"], r:"global" },
  { c:"islamic", l:"easy", t:"What word, said before beginning an action, means 'in the name of God' in Arabic?", a:"Bismillah", w:["Inshallah","Mashallah","Alhamdulillah"], r:"global" },
  { c:"islamic", l:"easy", t:"What Arabic phrase, said upon hearing good news, means 'praise be to God'?", a:"Alhamdulillah", w:["Astaghfirullah","Subhanallah","Allahu Akbar"], r:"global" },
  { c:"islamic", l:"easy", t:"What Arabic phrase, commonly heard at Islamic celebrations, means 'God is greatest'?", a:"Allahu Akbar", w:["Alhamdulillah","La ilaha illallah","Bismillah"], r:"global" },
  { c:"islamic", l:"easy", t:"What is the special month-long set of extra night prayers performed during Ramadan called?", a:"Tarawih", w:["Suhoor","Jumu'ah","Witr"], n:true, r:"global", o:true },
  { c:"islamic", l:"easy", t:"Which of the Quran's chapters, its shortest and most frequently recited, opens the book?", a:"Al-Fatiha", w:["Al-Baqarah","Yasin","Al-Ikhlas"], n:true, r:"mena" },
  { c:"islamic", l:"easy", t:"What do Muslims call a person who has memorised the entire Quran by heart?", a:"A hafiz", w:["A mufti","A qadi","A muezzin"], n:true, r:"global", o:true },
  { c:"islamic", l:"easy", t:"What is the person who calls the Adhan from a mosque called?", a:"The muezzin", w:["The imam","The mufti","The qadi"], n:true, r:"global", o:true },
  { c:"islamic", l:"easy", t:"What is a Muslim woman's headscarf commonly called?", a:"A hijab", w:["A sari","A kimono","A dirndl"], r:"global", o:true },
  { c:"islamic", l:"easy", t:"Which sacred well, near the Kaaba, is linked in Islamic tradition to Ibrahim's wife Hagar?", a:"The Zamzam Well", w:["The Well of Souls","The Silwan Spring","The Pool of Siloam"], n:true, r:"mena" },

  /* ---------------- medium ---------------- */
  { c:"islamic", l:"medium", t:"What is the minor Islamic pilgrimage to Mecca that, unlike the Hajj, can be performed at any time of year?", a:"The Umrah", w:["The Hijra","The Isra","The Ziyarah"], n:true, r:"mena", o:true },
  { c:"islamic", l:"medium", t:"Which night in the last ten days of Ramadan, on which the Quran is believed to have first been revealed, is considered holier than a thousand months?", a:"Laylat al-Qadr", w:["Laylat al-Bara'ah","Isra and Mi'raj","Ashura"], n:true, r:"mena" },
  { c:"islamic", l:"medium", t:"What is the name for the night journey in which Muhammad is said to have travelled from Mecca to Jerusalem in a single night?", a:"The Isra", w:["The Hijra","The Mi'raj","The Fath"], n:true, r:"mena" },
  { c:"islamic", l:"medium", t:"Which day of remembrance, observed on the 10th of Muharram, marks the day Musa (Moses) is believed to have been saved from Pharaoh?", a:"Ashura", w:["Mawlid","Laylat al-Qadr","Arafah"], n:true, r:"mena" },
  { c:"islamic", l:"medium", t:"What is the day on which pilgrims gather at Mount Arafat, considered the most important day of the Hajj, called?", a:"The Day of Arafah", w:["Laylat al-Qadr","Ashura","Yawm al-Nahr"], n:true, r:"mena" },
  { c:"islamic", l:"medium", t:"What is the annual celebration of the Prophet Muhammad's birth, observed in many Muslim communities, called?", a:"Mawlid", w:["Ashura","Isra and Mi'raj","Laylat al-Bara'ah"], n:true, r:"mena" },
  { c:"islamic", l:"medium", t:"What is the Islamic legal ruling given by a qualified scholar in response to a question called?", a:"A fatwa", w:["A hadith","A tafsir","A sunnah"], n:true, r:"global", o:true },
  { c:"islamic", l:"medium", t:"What is the field of Islamic jurisprudence, covering everyday religious and legal rulings, called?", a:"Fiqh", w:["Tafsir","Aqidah","Tasawwuf"], n:true, r:"global" },
  { c:"islamic", l:"medium", t:"What is the scholarly interpretation and exegesis of the Quran called?", a:"Tafsir", w:["Fiqh","Hadith","Sunnah"], n:true, r:"global" },
  { c:"islamic", l:"medium", t:"What is the term for the Prophet Muhammad's example and teachings, a key source of Islamic law alongside the Quran?", a:"The Sunnah", w:["The Hadith","The Fiqh","The Sharia"], n:true, r:"global" },
  { c:"islamic", l:"medium", t:"What is the comprehensive Islamic legal and moral code, derived from the Quran and Sunnah, called?", a:"Sharia", w:["Fiqh","Tafsir","Kalam"], r:"global" },
  { c:"islamic", l:"medium", t:"Which dynasty, ruling from Damascus, was the first hereditary caliphate in Islamic history?", a:"The Umayyad Caliphate", w:["The Abbasid Caliphate","The Fatimid Caliphate","The Ottoman Caliphate"], r:"mena" },
  { c:"islamic", l:"medium", t:"Which caliphate, ruling from Baghdad, presided over the height of the Islamic Golden Age?", a:"The Abbasid Caliphate", w:["The Umayyad Caliphate","The Seljuk Empire","The Mamluk Sultanate"], r:"mena" },
  { c:"islamic", l:"medium", t:"Which Muslim empire, ruled by a Sultan from Istanbul's Topkapi Palace, lasted into the early 20th century?", a:"The Ottoman Empire", w:["The Safavid Empire","The Mughal Empire","The Abbasid Caliphate"], r:"mena" },
  { c:"islamic", l:"medium", t:"Which empire, centred in Persia, made Shia Islam its state religion in the 16th century?", a:"The Safavid Empire", w:["The Ottoman Empire","The Mughal Empire","The Abbasid Caliphate"], r:"mena" },
  { c:"islamic", l:"medium", t:"Which Muslim empire ruled over most of the Indian subcontinent and built the Taj Mahal?", a:"The Mughal Empire", w:["The Ottoman Empire","The Safavid Empire","The Delhi Sultanate"], r:"asia" },
  { c:"islamic", l:"medium", t:"Which region of medieval Spain and Portugal, under Muslim rule for centuries, is known by its Arabic name?", a:"Al-Andalus", w:["Al-Maghrib","Al-Sham","Al-Jazirah"], r:"europe" },
  { c:"islamic", l:"medium", t:"Which Andalusian city was famed under Muslim rule for its Great Mosque and as a centre of learning?", a:"Córdoba", w:["Granada","Seville","Toledo"], r:"europe" },
  { c:"islamic", l:"medium", t:"Which West African empire, centred on the wealthy city of Timbuktu, became a major hub of Islamic scholarship?", a:"The Mali Empire", w:["The Songhai Empire","The Ghana Empire","The Kanem Empire"], r:"africa" },
  { c:"islamic", l:"medium", t:"Which Mali Empire ruler, famed for a lavish Hajj to Mecca, is often called the richest person in history?", a:"Mansa Musa", w:["Sundiata Keita","Askia Muhammad","Sonni Ali"], n:true, r:"africa", o:true },
  { c:"islamic", l:"medium", t:"Which West African empire, following Mali, was ruled by Askia Muhammad and centred on the Niger River?", a:"The Songhai Empire", w:["The Mali Empire","The Kanem-Bornu Empire","The Fulani Empire"], r:"africa" },
  { c:"islamic", l:"medium", t:"Which country, the world's most populous Muslim-majority nation, is in Southeast Asia?", a:"Indonesia", w:["Pakistan","Malaysia","Bangladesh"], r:"asia", o:true },
  { c:"islamic", l:"medium", t:"Which strait separates Muslim-majority Malaysia from Indonesia's island of Sumatra?", a:"The Strait of Malacca", w:["The Sunda Strait","The Strait of Hormuz","The Bosphorus"], r:"asia" },
  { c:"islamic", l:"medium", t:"Which mystical, devotional branch of Islam, associated with figures like Rumi, emphasises the inward search for God?", a:"Sufism", w:["Salafism","Kharijism","Mu'tazilism"], n:true, r:"global", o:true },
  { c:"islamic", l:"medium", t:"Which 13th-century Persian poet, beloved for mystical verse, founded the Sufi order known for its whirling dance?", a:"Rumi", w:["Hafez","Saadi","Omar Khayyam"], n:true, r:"mena", o:true },
  { c:"islamic", l:"medium", t:"What is the ritual washing Muslims perform before prayer called?", a:"Wudu", w:["Ghusl", "Tayammum","Istinja"], n:true, r:"global", o:true },
  { c:"islamic", l:"medium", t:"What is the full-body ritual purification bath, required after certain occasions, called?", a:"Ghusl", w:["Wudu","Tayammum","Istinja"], n:true, r:"global", o:true },
  { c:"islamic", l:"medium", t:"What is the dry ritual purification with sand or dust, used when water is unavailable, called?", a:"Tayammum", w:["Wudu","Ghusl","Istinja"], n:true, r:"global" },
  { c:"islamic", l:"medium", t:"What is the Islamic dietary term for food that is permissible to eat?", a:"Halal", w:["Kosher","Haram","Makruh"], r:"global", o:true },
  { c:"islamic", l:"medium", t:"What is the Islamic term for something forbidden, the opposite of halal?", a:"Haram", w:["Halal","Makruh","Mubah"], r:"global", o:true },
  { c:"islamic", l:"medium", t:"Which meat is forbidden to eat under Islamic dietary law?", a:"Pork", w:["Beef","Lamb","Chicken"], r:"global", o:true },
  { c:"islamic", l:"medium", t:"Which two of the Five Pillars concern giving to charity and travelling to Mecca?", a:"Zakat and Hajj", w:["Salah and Sawm","Shahada and Salah","Sawm and Zakat"], r:"global" },
  { c:"islamic", l:"medium", t:"What is the additional voluntary charity, beyond the obligatory Zakat, called?", a:"Sadaqah", w:["Zakat al-Fitr","Khums","Waqf"], n:true, r:"global", o:true },
  { c:"islamic", l:"medium", t:"What is the charitable endowment of property for religious or public benefit, common in Islamic history, called?", a:"A waqf", w:["A zakat","A sadaqah","A jizya"], n:true, r:"global" },
  { c:"islamic", l:"medium", t:"Which two branches make up the majority of Islam, historically split over the question of leadership after Muhammad?", a:"Sunni and Shia", w:["Sunni and Sufi","Shia and Ibadi","Sunni and Ibadi"], r:"global", o:true },
  { c:"islamic", l:"medium", t:"What is the honorific title for a descendant of the Prophet Muhammad, or a leader of an Islamic community, meaning 'leader' or 'commander'?", a:"Sayyid", w:["Sultan","Emir","Caliph"], n:true, r:"global" },
  { c:"islamic", l:"medium", t:"What is the title of the historical political-religious leader of the wider Muslim community, meaning 'successor'?", a:"Caliph", w:["Sultan","Emir","Imam"], r:"global", o:true },
  { c:"islamic", l:"medium", t:"Which script, developed for Arabic and used across the Islamic world, is famed for its decorative use in mosque architecture?", a:"Arabic calligraphy", w:["Cyrillic script","Devanagari script","Cuneiform script"], r:"global" },
  { c:"islamic", l:"medium", t:"What is the geometric, non-figurative decoration common in Islamic art and architecture, avoiding depictions of humans and animals, generally called?", a:"Arabesque", w:["Fresco","Mosaic tessera","Relief carving"], n:true, r:"global" },
  { c:"islamic", l:"medium", t:"Which famous blue-tiled mosque in Istanbul is formally named after Sultan Ahmed I?", a:"The Blue Mosque", w:["The Süleymaniye Mosque","Hagia Sophia","The Selimiye Mosque"], r:"mena", o:true },
  { c:"islamic", l:"medium", t:"Which Byzantine cathedral in Istanbul was converted into a mosque after the Ottoman conquest of Constantinople in 1453?", a:"Hagia Sophia", w:["The Blue Mosque","The Süleymaniye Mosque","The Selimiye Mosque"], r:"mena", o:true },
  { c:"islamic", l:"medium", t:"Which Ottoman sultan led the 1453 conquest of Constantinople?", a:"Mehmed II", w:["Suleiman the Magnificent","Selim I","Bayezid II"], n:true, r:"mena", o:true },
  { c:"islamic", l:"medium", t:"Which Ottoman sultan, known as 'the Magnificent', presided over the empire's 16th-century peak?", a:"Suleiman the Magnificent", w:["Mehmed II","Selim I","Osman I"], r:"mena", o:true },
  { c:"islamic", l:"medium", t:"What is the traditional Islamic form of banking that prohibits charging interest called?", a:"Islamic banking", w:["Microfinance","Cooperative banking","Sovereign banking"], r:"global" },
  { c:"islamic", l:"medium", t:"What is the interest, forbidden under Islamic finance, called in Arabic?", a:"Riba", w:["Zakat","Jizya","Khums"], n:true, r:"global" },
  { c:"islamic", l:"medium", t:"Which historic library and centre of learning in Baghdad, founded under the Abbasids, translated Greek, Persian and Indian works into Arabic?", a:"The House of Wisdom", w:["The Library of Alexandria","Al-Qarawiyyin","Al-Azhar"], n:true, r:"mena" },
  { c:"islamic", l:"medium", t:"Which university, founded in Fez, Morocco in 859 CE, is recognised as the oldest continuously operating institution of higher learning in the world?", a:"University of Al-Qarawiyyin", w:["Al-Azhar University","The House of Wisdom","Nizamiyya of Baghdad"], n:true, r:"africa" },
  { c:"islamic", l:"medium", t:"Which mosque and university in Cairo, founded in 970 CE, is one of the oldest in the Islamic world and a leading centre of Sunni scholarship?", a:"Al-Azhar", w:["Al-Qarawiyyin","The House of Wisdom","The Great Mosque of Kairouan"], n:true, r:"mena", o:true },
  { c:"islamic", l:"medium", t:"Which Tunisian city, founded by the Arab general Uqba ibn Nafi, is home to one of the oldest mosques in North Africa?", a:"Kairouan", w:["Tunis","Sousse","Sfax"], n:true, r:"africa" },

  /* ---------------- hard ---------------- */
  { c:"islamic", l:"hard", t:"Which Persian scholar's 9th-century book on algebra gave the subject its name?", a:"Al-Khwarizmi", w:["Al-Kindi","Al-Biruni","Al-Farabi"], n:true, r:"mena", o:true },
  { c:"islamic", l:"hard", t:"Which Persian polymath, known in the West as Avicenna, wrote 'The Canon of Medicine', a standard medical text for centuries?", a:"Ibn Sina", w:["Ibn Rushd","Al-Razi","Ibn al-Haytham"], n:true, r:"mena", o:true },
  { c:"islamic", l:"hard", t:"Which Andalusian philosopher, known in the West as Averroes, wrote influential commentaries on Aristotle?", a:"Ibn Rushd", w:["Ibn Sina","Al-Ghazali","Ibn Khaldun"], n:true, r:"europe", o:true },
  { c:"islamic", l:"hard", t:"Which 11th-century scholar, known in the West as Alhazen, is considered a father of the modern scientific method for his work on optics?", a:"Ibn al-Haytham", w:["Al-Khwarizmi","Ibn Sina","Al-Kindi"], n:true, r:"mena", o:true },
  { c:"islamic", l:"hard", t:"Which 14th-century North African scholar is regarded as a founder of the modern disciplines of historiography and sociology?", a:"Ibn Khaldun", w:["Ibn Battuta","Ibn Rushd","Al-Biruni"], n:true, r:"africa", o:true },
  { c:"islamic", l:"hard", t:"Which 14th-century Moroccan traveller journeyed across nearly the entire Islamic world, from West Africa to China, recording his travels?", a:"Ibn Battuta", w:["Ibn Khaldun","Ibn Fadlan","Al-Idrisi"], n:true, r:"africa", o:true },
  { c:"islamic", l:"hard", t:"Which Persian physician and philosopher, known in the West as Rhazes, distinguished measles from smallpox and headed hospitals in Baghdad?", a:"Al-Razi", w:["Ibn Sina","Al-Kindi","Ibn al-Haytham"], n:true, r:"mena" },
  { c:"islamic", l:"hard", t:"Which Muslim scholar-astronomer's estimate of Earth's circumference, made around the year 1000, was remarkably close to the modern figure?", a:"Al-Biruni", w:["Al-Khwarizmi","Al-Battani","Ibn al-Haytham"], n:true, r:"mena" },
  { c:"islamic", l:"hard", t:"Which influential 11th-century theologian's critique of philosophy, 'The Incoherence of the Philosophers', shaped later Islamic thought?", a:"Al-Ghazali", w:["Ibn Rushd","Ibn Sina","Al-Ash'ari"], n:true, r:"mena" },
  { c:"islamic", l:"hard", t:"Which Persian polymath is credited with foundational advances in algebra and wrote poetry collected as the 'Rubaiyat'?", a:"Omar Khayyam", w:["Rumi","Hafez","Saadi"], n:true, r:"mena", o:true },
  { c:"islamic", l:"hard", t:"Which Muslim scholar, court astronomer to the Mongol Ilkhanate, built the influential Maragheh observatory in Persia?", a:"Nasir al-Din al-Tusi", w:["Al-Battani","Ulugh Beg","Al-Biruni"], n:true, r:"mena" },
  { c:"islamic", l:"hard", t:"Which Timurid ruler and astronomer built a major 15th-century observatory in Samarkand?", a:"Ulugh Beg", w:["Timur","Babur","Al-Tusi"], n:true, r:"asia" },
  { c:"islamic", l:"hard", t:"Which Muslim conqueror founded the Mughal Empire in 1526 after defeating the Delhi Sultanate at the Battle of Panipat?", a:"Babur", w:["Akbar","Timur","Aurangzeb"], n:true, r:"asia" },
  { c:"islamic", l:"hard", t:"Which Mughal emperor built the Taj Mahal as a mausoleum for his wife Mumtaz Mahal?", a:"Shah Jahan", w:["Akbar","Babur","Aurangzeb"], n:true, r:"asia", o:true },
  { c:"islamic", l:"hard", t:"Which Mughal emperor is best known for promoting religious tolerance and a syncretic policy across his diverse empire?", a:"Akbar", w:["Shah Jahan","Aurangzeb","Babur"], n:true, r:"asia" },
  { c:"islamic", l:"hard", t:"Which Muslim Kurdish general founded the Ayyubid dynasty and recaptured Jerusalem from the Crusaders in 1187?", a:"Saladin", w:["Baibars","Nur ad-Din","Al-Kamil"], n:true, r:"mena", o:true },
  { c:"islamic", l:"hard", t:"Which Mamluk sultan commanded the decisive victory over the Mongols at the Battle of Ain Jalut in 1260?", a:"Qutuz", w:["Baibars","Saladin","Al-Kamil"], n:true, r:"mena" },
  { c:"islamic", l:"hard", t:"Which 8th-century Umayyad-founded emirate, later a caliphate, ruled Islamic Spain from its capital at Córdoba?", a:"The Emirate of Córdoba", w:["The Emirate of Granada","The Almoravid Emirate","The Almohad Caliphate"], n:true, r:"europe" },
  { c:"islamic", l:"hard", t:"Which was the last Muslim kingdom in Spain, falling to the Catholic Monarchs in 1492?", a:"The Emirate of Granada", w:["The Emirate of Córdoba","The Almohad Caliphate","The Taifa of Seville"], n:true, r:"europe", o:true },
  { c:"islamic", l:"hard", t:"Which palace and fortress complex in Granada is the best-preserved monument of Islamic Spain?", a:"The Alhambra", w:["The Mezquita","The Giralda","The Alcázar"], n:true, r:"europe", o:true },
  { c:"islamic", l:"hard", t:"Which former mosque in Córdoba, now a cathedral, is famed for its forest of red-and-white striped double arches?", a:"The Mezquita", w:["The Alhambra","The Giralda","Medina Azahara"], n:true, r:"europe", o:true },
  { c:"islamic", l:"hard", t:"Which 8th-century Berber and Arab military leader led the initial Muslim conquest of Visigothic Spain?", a:"Tariq ibn Ziyad", w:["Musa ibn Nusayr","Abd al-Rahman I","Uqba ibn Nafi"], n:true, r:"europe" },
  { c:"islamic", l:"hard", t:"Which strait, named after the general who led the Muslim conquest of Spain, separates Spain from Morocco?", a:"The Strait of Gibraltar", w:["The Bosphorus","The Strait of Hormuz","The Dardanelles"], r:"mena" },
  { c:"islamic", l:"hard", t:"Which Umayyad prince fled the Abbasid overthrow of his dynasty and founded the independent Emirate of Córdoba?", a:"Abd al-Rahman I", w:["Tariq ibn Ziyad","Musa ibn Nusayr","Al-Hakam II"], n:true, r:"europe" },
  { c:"islamic", l:"hard", t:"Which Shia dynasty, claiming descent from the Prophet's daughter Fatima, founded Cairo and ruled much of North Africa and the Levant?", a:"The Fatimid Caliphate", w:["The Abbasid Caliphate","The Umayyad Caliphate","The Ayyubid dynasty"], n:true, r:"mena" },
  { c:"islamic", l:"hard", t:"Which North African Berber dynasty, founded on a Sufi religious movement, ruled Morocco and Al-Andalus in the 11th-12th centuries?", a:"The Almoravid dynasty", w:["The Almohad dynasty","The Fatimid dynasty","The Idrisid dynasty"], n:true, r:"africa" },
  { c:"islamic", l:"hard", t:"Which Somali sultanate, a major medieval trading power on the Horn of Africa, controlled routes across the Gulf of Aden?", a:"The Adal Sultanate", w:["The Ajuran Sultanate","The Sultanate of Ifat","The Warsangali Sultanate"], n:true, r:"africa" },
  { c:"islamic", l:"hard", t:"Which East African city-state, a major Swahili Islamic trading port, gave its name to a strait separating it from mainland Tanzania?", a:"Zanzibar", w:["Mombasa","Kilwa","Lamu"], n:true, r:"africa", o:true },
  { c:"islamic", l:"hard", t:"Which medieval Swahili coast city-state, now a ruined UNESCO World Heritage Site in Tanzania, was one of East Africa's wealthiest Islamic trading ports?", a:"Kilwa Kisiwani", w:["Zanzibar Stone Town","Lamu","Mombasa"], n:true, r:"africa" },
  { c:"islamic", l:"hard", t:"Which sultanate, centred on the Bosphorus city later renamed Istanbul, was ruled under a system pairing the sultan with a chief religious authority called the Sheikh al-Islam?", a:"The Ottoman Empire", w:["The Seljuk Empire","The Ayyubid Sultanate","The Mamluk Sultanate"], r:"mena" },
  { c:"islamic", l:"hard", t:"Which Turkic dynasty, ruling much of Central Asia and the Middle East before the Ottomans, won the pivotal Battle of Manzikert against the Byzantines in 1071?", a:"The Seljuk Empire", w:["The Ottoman Empire","The Ghaznavid Empire","The Timurid Empire"], n:true, r:"mena" },
  { c:"islamic", l:"hard", t:"Which Central Asian conqueror, whose empire preceded the Mughals, is buried in the Gur-e-Amir mausoleum in Samarkand?", a:"Timur (Tamerlane)", w:["Genghis Khan","Babur","Ulugh Beg"], n:true, r:"asia", o:true },
  { c:"islamic", l:"hard", t:"Which sultanate, based in Delhi, ruled much of northern India for over three centuries before the Mughals?", a:"The Delhi Sultanate", w:["The Mughal Empire","The Bahmani Sultanate","The Bengal Sultanate"], n:true, r:"asia" },
  { c:"islamic", l:"hard", t:"Which historic maritime sultanate on the Malay Peninsula became a major centre for spreading Islam across Southeast Asia?", a:"The Sultanate of Malacca", w:["The Sultanate of Brunei","The Sultanate of Aceh","The Sultanate of Johor"], n:true, r:"asia" },
  { c:"islamic", l:"hard", t:"Which Sumatran sultanate, a major power in the spread of Islam in Southeast Asia, is sometimes called the 'Veranda of Mecca'?", a:"The Sultanate of Aceh", w:["The Sultanate of Malacca","The Sultanate of Brunei","The Sultanate of Demak"], n:true, r:"asia" },
  { c:"islamic", l:"hard", t:"Which tax was historically levied on non-Muslim subjects living under Islamic rule, in place of the Zakat required of Muslims?", a:"Jizya", w:["Riba","Khums","Waqf"], n:true, r:"global" },
  { c:"islamic", l:"hard", t:"What is the Islamic legal concept of scholarly consensus, one of the traditional sources of Islamic law alongside the Quran and Sunnah?", a:"Ijma", w:["Qiyas","Ijtihad","Istihsan"], n:true, r:"global" },
  { c:"islamic", l:"hard", t:"What is the Islamic legal method of reasoning by analogy, used to derive rulings for situations not directly addressed in scripture?", a:"Qiyas", w:["Ijma","Ijtihad","Istihsan"], n:true, r:"global" },
  { c:"islamic", l:"hard", t:"What is the term for independent legal reasoning by a qualified Islamic scholar to reach a ruling?", a:"Ijtihad", w:["Taqlid","Ijma","Qiyas"], n:true, r:"global" },
  { c:"islamic", l:"hard", t:"Which of the four major Sunni schools of jurisprudence is named after the 8th-century scholar Abu Hanifa and is the most widely followed today?", a:"The Hanafi school", w:["The Maliki school","The Shafi'i school","The Hanbali school"], n:true, r:"global" },
  { c:"islamic", l:"hard", t:"Which Sunni school of jurisprudence, founded by Malik ibn Anas, is dominant across much of North and West Africa?", a:"The Maliki school", w:["The Hanafi school","The Shafi'i school","The Hanbali school"], n:true, r:"africa" },
  { c:"islamic", l:"hard", t:"Which conservative Sunni school of jurisprudence, founded by Ahmad ibn Hanbal, is the official school of Saudi Arabia?", a:"The Hanbali school", w:["The Hanafi school","The Maliki school","The Shafi'i school"], n:true, r:"mena" },
  { c:"islamic", l:"hard", t:"Which branch of Shia Islam, the largest, holds that twelve imams succeeded the Prophet Muhammad?", a:"Twelver Shia Islam", w:["Ismaili Shia Islam","Zaidi Shia Islam","Ibadi Islam"], n:true, r:"mena" },
  { c:"islamic", l:"hard", t:"Which small, distinct branch of Islam, neither Sunni nor Shia, is the majority religion in Oman?", a:"Ibadi Islam", w:["Zaidi Islam","Ismaili Islam","Alawite Islam"], n:true, r:"mena" },
  { c:"islamic", l:"hard", t:"Which Sufi order, founded in Konya and famed for its spinning devotional dance, is popularly known as the 'whirling dervishes'?", a:"The Mevlevi Order", w:["The Naqshbandi Order","The Qadiriyya Order","The Chishti Order"], n:true, r:"mena" },
  { c:"islamic", l:"hard", t:"Which Sufi order, founded by Abdul Qadir Gilani in Baghdad, is one of the oldest and most widespread Sufi orders?", a:"The Qadiriyya Order", w:["The Mevlevi Order","The Naqshbandi Order","The Suhrawardiyya Order"], n:true, r:"mena" },
  { c:"islamic", l:"hard", t:"Which 18th-century reform movement, originating on the Arabian Peninsula, shaped the religious character of the modern Saudi state?", a:"Wahhabism", w:["Salafism","Sufism","Deobandism"], n:true, r:"mena" },
  { c:"islamic", l:"hard", t:"Which Indian Islamic reform movement and seminary, founded in 1866, gave its name to a global school of Sunni thought?", a:"Deobandi", w:["Barelvi","Ahl-i Hadith","Jamaat-e-Islami"], n:true, r:"asia" },

  ];
  globalThis.ANSWER_IT_CURATED = (globalThis.ANSWER_IT_CURATED || []).concat(B);
})();
